import config from './config'
const API_config = {
  Users: {
    login: `${config.api}/accounts/login`,
    list: `${config.api}/accounts`,
    create: `${config.api}/accounts`,
    update: `${config.api}/accounts`,
    delete: `${config.api}/accounts`,
  },
  products: {
    list: `${config.api}/products`,
    list_add: `${config.api}/products/listadd`,
    create: `${config.api}/products`,
    update: `${config.api}/products`,
    delete: `${config.api}/products`,
  },
  customers: {
    list: `${config.api}/customers`,
    list_add: `${config.api}/customers/listadd`,
    create: `${config.api}/customers`,
    update: `${config.api}/customers`,
    delete: `${config.api}/customers`,
  },
  employees: {
    list: `${config.api}/employees`,
    list_add: `${config.api}/employees/listadd`,
    list_detail: `${config.api}/employees/listdetail`,
    create: `${config.api}/employees`,
    update: `${config.api}/employees`,
    delete: `${config.api}/employees`,
    stop: `${config.api}/employees/stop`,
    backdata: `${config.api}/employees/backdata/all`,
    updatestatus: `${config.api}/employees/backdata`,
  },
  orders: {
    list: `${config.api}/orders`,
    list_detail: `${config.api}/orders/listdetail`,
    create: `${config.api}/orders`,
    update: `${config.api}/orders`,
    delete: `${config.api}/orders`,
    stop: `${config.api}/orders/stop`,
    backdata: `${config.api}/orders/backdata`,
    updatestatus: `${config.api}/orders/updatestatus`,
  },
  order_details: {
    list: `${config.api}/order_details`,
    list_detail: `${config.api}/order_details/listdetail`,
    create: `${config.api}/order_details`,
    update: `${config.api}/order_details`,
    delete: `${config.api}/order_details`,
    stop: `${config.api}/order_details/stop`,
    backdata: `${config.api}/order_details/backdata`,
    updatestatus: `${config.api}/order_details/updatestatus`,
  },
  shippers: {
    list: `${config.api}/shippers`,
    create: `${config.api}/shippers`,
    update: `${config.api}/shippers`,
    delete: `${config.api}/shippers`,
  },
  suppliers: {
    list: `${config.api}/suppliers`,
    create: `${config.api}/suppliers`,
    update: `${config.api}/suppliers`,
    delete: `${config.api}/suppliers`,
  },
  genres: {
    list: `${config.api}/genres`,
    create: `${config.api}/genres`,
    update: `${config.api}/genres`,
    delete: `${config.api}/genres`,
  },
  store_products: {
    list: `${config.api}/store_products`,
    list_add: `${config.api}/store_products/listadd`,
    list_byid: `${config.api}/store_products/listbyid`,
    create: `${config.api}/store_products`,
    update: `${config.api}/store_products`,
    delete: `${config.api}/store_products`,
    stop: `${config.api}/store_products/stop`,
    backdata: `${config.api}/store_products/backdata`,
    updatestatus: `${config.api}/store_products/updatestatus`,
  },
  store: {
    list: `${config.api}/store`,
    list_add: `${config.api}/store/listadd`,
    create: `${config.api}/store`,
    update: `${config.api}/store`,
    delete: `${config.api}/store`,
  },
}
export default API_config
